// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

#ifndef TD_CFDI_HXX
#define TD_CFDI_HXX

#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_TREE_USE_CHAR
#define XSD_CXX_TREE_USE_CHAR
#endif

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (XSD_INT_VERSION != 4000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/types.hxx>

#include <xsd/cxx/xml/error-handler.hxx>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

#include <xsd/cxx/tree/parsing.hxx>
#include <xsd/cxx/tree/parsing/byte.hxx>
#include <xsd/cxx/tree/parsing/unsigned-byte.hxx>
#include <xsd/cxx/tree/parsing/short.hxx>
#include <xsd/cxx/tree/parsing/unsigned-short.hxx>
#include <xsd/cxx/tree/parsing/int.hxx>
#include <xsd/cxx/tree/parsing/unsigned-int.hxx>
#include <xsd/cxx/tree/parsing/long.hxx>
#include <xsd/cxx/tree/parsing/unsigned-long.hxx>
#include <xsd/cxx/tree/parsing/boolean.hxx>
#include <xsd/cxx/tree/parsing/float.hxx>
#include <xsd/cxx/tree/parsing/double.hxx>
#include <xsd/cxx/tree/parsing/decimal.hxx>

namespace xml_schema
{
  // anyType and anySimpleType.
  //
  typedef ::xsd::cxx::tree::type type;
  typedef ::xsd::cxx::tree::simple_type< char, type > simple_type;
  typedef ::xsd::cxx::tree::type container;

  // 8-bit
  //
  typedef signed char byte;
  typedef unsigned char unsigned_byte;

  // 16-bit
  //
  typedef short short_;
  typedef unsigned short unsigned_short;

  // 32-bit
  //
  typedef int int_;
  typedef unsigned int unsigned_int;

  // 64-bit
  //
  typedef long long long_;
  typedef unsigned long long unsigned_long;

  // Supposed to be arbitrary-length integral types.
  //
  typedef long long integer;
  typedef long long non_positive_integer;
  typedef unsigned long long non_negative_integer;
  typedef unsigned long long positive_integer;
  typedef long long negative_integer;

  // Boolean.
  //
  typedef bool boolean;

  // Floating-point types.
  //
  typedef float float_;
  typedef double double_;
  typedef double decimal;

  // String types.
  //
  typedef ::xsd::cxx::tree::string< char, simple_type > string;
  typedef ::xsd::cxx::tree::normalized_string< char, string > normalized_string;
  typedef ::xsd::cxx::tree::token< char, normalized_string > token;
  typedef ::xsd::cxx::tree::name< char, token > name;
  typedef ::xsd::cxx::tree::nmtoken< char, token > nmtoken;
  typedef ::xsd::cxx::tree::nmtokens< char, simple_type, nmtoken > nmtokens;
  typedef ::xsd::cxx::tree::ncname< char, name > ncname;
  typedef ::xsd::cxx::tree::language< char, token > language;

  // ID/IDREF.
  //
  typedef ::xsd::cxx::tree::id< char, ncname > id;
  typedef ::xsd::cxx::tree::idref< char, ncname, type > idref;
  typedef ::xsd::cxx::tree::idrefs< char, simple_type, idref > idrefs;

  // URI.
  //
  typedef ::xsd::cxx::tree::uri< char, simple_type > uri;

  // Qualified name.
  //
  typedef ::xsd::cxx::tree::qname< char, simple_type, uri, ncname > qname;

  // Binary.
  //
  typedef ::xsd::cxx::tree::buffer< char > buffer;
  typedef ::xsd::cxx::tree::base64_binary< char, simple_type > base64_binary;
  typedef ::xsd::cxx::tree::hex_binary< char, simple_type > hex_binary;

  // Date/time.
  //
  typedef ::xsd::cxx::tree::time_zone time_zone;
  typedef ::xsd::cxx::tree::date< char, simple_type > date;
  typedef ::xsd::cxx::tree::date_time< char, simple_type > date_time;
  typedef ::xsd::cxx::tree::duration< char, simple_type > duration;
  typedef ::xsd::cxx::tree::gday< char, simple_type > gday;
  typedef ::xsd::cxx::tree::gmonth< char, simple_type > gmonth;
  typedef ::xsd::cxx::tree::gmonth_day< char, simple_type > gmonth_day;
  typedef ::xsd::cxx::tree::gyear< char, simple_type > gyear;
  typedef ::xsd::cxx::tree::gyear_month< char, simple_type > gyear_month;
  typedef ::xsd::cxx::tree::time< char, simple_type > time;

  // Entity.
  //
  typedef ::xsd::cxx::tree::entity< char, ncname > entity;
  typedef ::xsd::cxx::tree::entities< char, simple_type, entity > entities;

  typedef ::xsd::cxx::tree::content_order content_order;
  // Flags and properties.
  //
  typedef ::xsd::cxx::tree::flags flags;
  typedef ::xsd::cxx::tree::properties< char > properties;

  // Parsing/serialization diagnostics.
  //
  typedef ::xsd::cxx::tree::severity severity;
  typedef ::xsd::cxx::tree::error< char > error;
  typedef ::xsd::cxx::tree::diagnostics< char > diagnostics;

  // Exceptions.
  //
  typedef ::xsd::cxx::tree::exception< char > exception;
  typedef ::xsd::cxx::tree::bounds< char > bounds;
  typedef ::xsd::cxx::tree::duplicate_id< char > duplicate_id;
  typedef ::xsd::cxx::tree::parsing< char > parsing;
  typedef ::xsd::cxx::tree::expected_element< char > expected_element;
  typedef ::xsd::cxx::tree::unexpected_element< char > unexpected_element;
  typedef ::xsd::cxx::tree::expected_attribute< char > expected_attribute;
  typedef ::xsd::cxx::tree::unexpected_enumerator< char > unexpected_enumerator;
  typedef ::xsd::cxx::tree::expected_text_content< char > expected_text_content;
  typedef ::xsd::cxx::tree::no_prefix_mapping< char > no_prefix_mapping;

  // Error handler callback interface.
  //
  typedef ::xsd::cxx::xml::error_handler< char > error_handler;

  // DOM interaction.
  //
  namespace dom
  {
    // Automatic pointer for DOMDocument.
    //
    using ::xsd::cxx::xml::dom::auto_ptr;

#ifndef XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
#define XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
    // DOM user data key for back pointers to tree nodes.
    //
    const XMLCh* const tree_node_key = ::xsd::cxx::tree::user_data_keys::node;
#endif
  }
}

// Forward declarations.
//
namespace sitio_internet
{
  namespace cfd
  {
    namespace tipoDatos
    {
      namespace tdCFDI
      {
        class t_CURP;
        class t_Importe;
        class t_Fecha;
        class t_ImporteMXN;
        class t_CuentaBancaria;
        class t_RFC;
        class t_RFC_PM;
        class t_RFC_PF;
        class t_FechaHora;
        class t_FechaH;
        class t_Descrip100;
        class t_NumeroDomicilio;
        class t_Referencia;
        class t_Descrip120;
        class t_TipoCambio;
      }
    }
  }
}


#include <memory>    // ::std::auto_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

namespace sitio_internet
{
  namespace cfd
  {
    namespace tipoDatos
    {
      namespace tdCFDI
      {
        class t_CURP: public ::xml_schema::string
        {
          public:
          // Constructors.
          //
          t_CURP ();

          t_CURP (const char*);

          t_CURP (const ::std::string&);

          t_CURP (const ::xml_schema::string&);

          t_CURP (const ::xercesc::DOMElement& e,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

          t_CURP (const ::xercesc::DOMAttr& a,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

          t_CURP (const ::std::string& s,
                  const ::xercesc::DOMElement* e,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

          t_CURP (const t_CURP& x,
                  ::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0);

          virtual t_CURP*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          virtual 
          ~t_CURP ();
        };

        class t_Importe: public ::xsd::cxx::tree::fundamental_base< ::xml_schema::decimal, char, ::xml_schema::simple_type, ::xsd::cxx::tree::schema_type::decimal >
        {
          public:
          // Constructors.
          //
          t_Importe (const ::xml_schema::decimal&);

          t_Importe (const ::xercesc::DOMElement& e,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

          t_Importe (const ::xercesc::DOMAttr& a,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

          t_Importe (const ::std::string& s,
                     const ::xercesc::DOMElement* e,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

          t_Importe (const t_Importe& x,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

          virtual t_Importe*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          virtual 
          ~t_Importe ();
        };

        class t_Fecha: public ::xml_schema::date
        {
          public:
          // Constructors.
          //
          t_Fecha (const ::xml_schema::date&);

          t_Fecha (const ::xercesc::DOMElement& e,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

          t_Fecha (const ::xercesc::DOMAttr& a,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

          t_Fecha (const ::std::string& s,
                   const ::xercesc::DOMElement* e,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

          t_Fecha (const t_Fecha& x,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

          virtual t_Fecha*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          virtual 
          ~t_Fecha ();
        };

        class t_ImporteMXN: public ::xsd::cxx::tree::fundamental_base< ::xml_schema::decimal, char, ::xml_schema::simple_type, ::xsd::cxx::tree::schema_type::decimal >
        {
          public:
          // Constructors.
          //
          t_ImporteMXN (const ::xml_schema::decimal&);

          t_ImporteMXN (const ::xercesc::DOMElement& e,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          t_ImporteMXN (const ::xercesc::DOMAttr& a,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          t_ImporteMXN (const ::std::string& s,
                        const ::xercesc::DOMElement* e,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          t_ImporteMXN (const t_ImporteMXN& x,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          virtual t_ImporteMXN*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          virtual 
          ~t_ImporteMXN ();
        };

        class t_CuentaBancaria: public ::xsd::cxx::tree::fundamental_base< ::xml_schema::integer, char, ::xml_schema::simple_type >
        {
          public:
          // Constructors.
          //
          t_CuentaBancaria (const ::xml_schema::integer&);

          t_CuentaBancaria (const ::xercesc::DOMElement& e,
                            ::xml_schema::flags f = 0,
                            ::xml_schema::container* c = 0);

          t_CuentaBancaria (const ::xercesc::DOMAttr& a,
                            ::xml_schema::flags f = 0,
                            ::xml_schema::container* c = 0);

          t_CuentaBancaria (const ::std::string& s,
                            const ::xercesc::DOMElement* e,
                            ::xml_schema::flags f = 0,
                            ::xml_schema::container* c = 0);

          t_CuentaBancaria (const t_CuentaBancaria& x,
                            ::xml_schema::flags f = 0,
                            ::xml_schema::container* c = 0);

          virtual t_CuentaBancaria*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          virtual 
          ~t_CuentaBancaria ();
        };

        class t_RFC: public ::xml_schema::string
        {
          public:
          // Constructors.
          //
          t_RFC ();

          t_RFC (const char*);

          t_RFC (const ::std::string&);

          t_RFC (const ::xml_schema::string&);

          t_RFC (const ::xercesc::DOMElement& e,
                 ::xml_schema::flags f = 0,
                 ::xml_schema::container* c = 0);

          t_RFC (const ::xercesc::DOMAttr& a,
                 ::xml_schema::flags f = 0,
                 ::xml_schema::container* c = 0);

          t_RFC (const ::std::string& s,
                 const ::xercesc::DOMElement* e,
                 ::xml_schema::flags f = 0,
                 ::xml_schema::container* c = 0);

          t_RFC (const t_RFC& x,
                 ::xml_schema::flags f = 0,
                 ::xml_schema::container* c = 0);

          virtual t_RFC*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          virtual 
          ~t_RFC ();
        };

        class t_RFC_PM: public ::xml_schema::string
        {
          public:
          // Constructors.
          //
          t_RFC_PM ();

          t_RFC_PM (const char*);

          t_RFC_PM (const ::std::string&);

          t_RFC_PM (const ::xml_schema::string&);

          t_RFC_PM (const ::xercesc::DOMElement& e,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

          t_RFC_PM (const ::xercesc::DOMAttr& a,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

          t_RFC_PM (const ::std::string& s,
                    const ::xercesc::DOMElement* e,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

          t_RFC_PM (const t_RFC_PM& x,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

          virtual t_RFC_PM*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          virtual 
          ~t_RFC_PM ();
        };

        class t_RFC_PF: public ::xml_schema::string
        {
          public:
          // Constructors.
          //
          t_RFC_PF ();

          t_RFC_PF (const char*);

          t_RFC_PF (const ::std::string&);

          t_RFC_PF (const ::xml_schema::string&);

          t_RFC_PF (const ::xercesc::DOMElement& e,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

          t_RFC_PF (const ::xercesc::DOMAttr& a,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

          t_RFC_PF (const ::std::string& s,
                    const ::xercesc::DOMElement* e,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

          t_RFC_PF (const t_RFC_PF& x,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

          virtual t_RFC_PF*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          virtual 
          ~t_RFC_PF ();
        };

        class t_FechaHora: public ::xml_schema::date_time
        {
          public:
          // Constructors.
          //
          t_FechaHora (const ::xml_schema::date_time&);

          t_FechaHora (const ::xercesc::DOMElement& e,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

          t_FechaHora (const ::xercesc::DOMAttr& a,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

          t_FechaHora (const ::std::string& s,
                       const ::xercesc::DOMElement* e,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

          t_FechaHora (const t_FechaHora& x,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

          virtual t_FechaHora*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          virtual 
          ~t_FechaHora ();
        };

        class t_FechaH: public ::xml_schema::date_time
        {
          public:
          // Constructors.
          //
          t_FechaH (const ::xml_schema::date_time&);

          t_FechaH (const ::xercesc::DOMElement& e,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

          t_FechaH (const ::xercesc::DOMAttr& a,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

          t_FechaH (const ::std::string& s,
                    const ::xercesc::DOMElement* e,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

          t_FechaH (const t_FechaH& x,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

          virtual t_FechaH*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          virtual 
          ~t_FechaH ();
        };

        class t_Descrip100: public ::xml_schema::string
        {
          public:
          // Constructors.
          //
          t_Descrip100 ();

          t_Descrip100 (const char*);

          t_Descrip100 (const ::std::string&);

          t_Descrip100 (const ::xml_schema::string&);

          t_Descrip100 (const ::xercesc::DOMElement& e,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          t_Descrip100 (const ::xercesc::DOMAttr& a,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          t_Descrip100 (const ::std::string& s,
                        const ::xercesc::DOMElement* e,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          t_Descrip100 (const t_Descrip100& x,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          virtual t_Descrip100*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          virtual 
          ~t_Descrip100 ();
        };

        class t_NumeroDomicilio: public ::xml_schema::string
        {
          public:
          // Constructors.
          //
          t_NumeroDomicilio ();

          t_NumeroDomicilio (const char*);

          t_NumeroDomicilio (const ::std::string&);

          t_NumeroDomicilio (const ::xml_schema::string&);

          t_NumeroDomicilio (const ::xercesc::DOMElement& e,
                             ::xml_schema::flags f = 0,
                             ::xml_schema::container* c = 0);

          t_NumeroDomicilio (const ::xercesc::DOMAttr& a,
                             ::xml_schema::flags f = 0,
                             ::xml_schema::container* c = 0);

          t_NumeroDomicilio (const ::std::string& s,
                             const ::xercesc::DOMElement* e,
                             ::xml_schema::flags f = 0,
                             ::xml_schema::container* c = 0);

          t_NumeroDomicilio (const t_NumeroDomicilio& x,
                             ::xml_schema::flags f = 0,
                             ::xml_schema::container* c = 0);

          virtual t_NumeroDomicilio*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          virtual 
          ~t_NumeroDomicilio ();
        };

        class t_Referencia: public ::xml_schema::string
        {
          public:
          // Constructors.
          //
          t_Referencia ();

          t_Referencia (const char*);

          t_Referencia (const ::std::string&);

          t_Referencia (const ::xml_schema::string&);

          t_Referencia (const ::xercesc::DOMElement& e,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          t_Referencia (const ::xercesc::DOMAttr& a,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          t_Referencia (const ::std::string& s,
                        const ::xercesc::DOMElement* e,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          t_Referencia (const t_Referencia& x,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          virtual t_Referencia*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          virtual 
          ~t_Referencia ();
        };

        class t_Descrip120: public ::xml_schema::string
        {
          public:
          // Constructors.
          //
          t_Descrip120 ();

          t_Descrip120 (const char*);

          t_Descrip120 (const ::std::string&);

          t_Descrip120 (const ::xml_schema::string&);

          t_Descrip120 (const ::xercesc::DOMElement& e,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          t_Descrip120 (const ::xercesc::DOMAttr& a,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          t_Descrip120 (const ::std::string& s,
                        const ::xercesc::DOMElement* e,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          t_Descrip120 (const t_Descrip120& x,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          virtual t_Descrip120*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          virtual 
          ~t_Descrip120 ();
        };

        class t_TipoCambio: public ::xsd::cxx::tree::fundamental_base< ::xml_schema::decimal, char, ::xml_schema::simple_type, ::xsd::cxx::tree::schema_type::decimal >
        {
          public:
          // Constructors.
          //
          t_TipoCambio (const ::xml_schema::decimal&);

          t_TipoCambio (const ::xercesc::DOMElement& e,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          t_TipoCambio (const ::xercesc::DOMAttr& a,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          t_TipoCambio (const ::std::string& s,
                        const ::xercesc::DOMElement* e,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          t_TipoCambio (const t_TipoCambio& x,
                        ::xml_schema::flags f = 0,
                        ::xml_schema::container* c = 0);

          virtual t_TipoCambio*
          _clone (::xml_schema::flags f = 0,
                  ::xml_schema::container* c = 0) const;

          virtual 
          ~t_TipoCambio ();
        };
      }
    }
  }
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace sitio_internet
{
  namespace cfd
  {
    namespace tipoDatos
    {
      namespace tdCFDI
      {
      }
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // TD_CFDI_HXX
